accounts/urls.py
from django.urls import path
from .views import (
    signup_view,
    login_view,
    logout_view,
)

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

articles/urls.py
from django.urls import path

from .views import(
    article_list,
    article_detail,
    article_create,
)

app_name = 'articles'

urlpatterns = [
    path('', article_list, name='article-list'),
    path('create/', article_create, name='article-create'),
    path('<slug:slug>', article_detail, name='article-detail'),
]

djangoplaylist/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from .views import(
    homepage,
    about
)
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.article_list, name='home'),
    path('about/', about),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name="password_reset"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author  = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return f'{self.body[:50]}...'

accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
        class Meta:
            model = User
            fields = [
                'username',
                'email',
                'password1',
                'password2',
            ]       

articles/forms.py
from django import forms
from .models import Article

class CreateArticle(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            'title',
            'body',
            'slug',
            'thumb'
        ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from .forms import CreateUserForm

# Create your views here.

# Signup
def signup_view(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Login the user
            login(request, user)
            return redirect('articles:article-list')
    else:
        form = CreateUserForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

# Login
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Login the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect('articles:article-list')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

# Logout
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:article-list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .forms import CreateArticle

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    context = {
        'articles': articles
    }
    return render(request, 'articles/article_list.html', context)

def article_detail(request, slug):
    article = Article.objects.get(slug = slug)
    context = {
        'article': article
    }
    return render(request, 'articles/article_detail.html', context)

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:article-list')
    else:
        form = CreateArticle()
    context = {
        'form': form
    }
    return render(request, 'articles/article_create.html', context)

djangoplaylist/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}
  {{ form }}
  {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
  {% endif %}
  <input type="submit" name="" value="Login">
</form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Signup</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" name="" value="Signup">
</form>
{% endblock content %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %} {% block content %}
<div class="article-create">
    <h2>Create an Awesome New Article</h2>
    <form class="site-form" action="{% url 'articles:article-create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form }}
        <input type="submit" value="create">
    </form>
</div>
<script src="/static/slugify.js"></script>

{% endblock content %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %} {% load static %} {% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" alt="">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock content %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %} {% load static %} {% block content %}
<h1>Article List</h1>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <h2><a href="{% url 'articles:article-detail' article.slug %}">{{ article.title }}</a></h2>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">Added by {{ article.author.username }}</p>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About us</h1>
    <p>We like django</p>
  </body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">
  </head>
  <body>
    <div class="wrapper">
      <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
              <ul>
                {% if user.is_authenticated %}
                <li>
                  <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                  </form>
                </li>
                <li><a href="{% url 'articles:article-create' %}" class="highlight">Create New Article</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
              </ul>
            </nav>
      </header>
      <div class="wrapper">
          {% block content %}
          {% endblock content %}
      </div>
    </div>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the Homepage</h1>
    <p>Welcome to Django Playlisst</p>
  </body>
</html>